---
# master_ep : master control-plane endpoint
kubernetes_role: control_plane
calico_manifest_version: "v3.29.0"
kubernetes_kubeadm_init_command: "kubeadm init --control-plane-endpoint {{ keepalived_virtual_ip_address }}:{{ haproxy_frontend_port }} --upload-certs"
