---
kubernetes_role: control_plane
calico_manifest_version: "v3.29.0"

cni_plugins_config_files:
  - filename: '10-crio-bridge.conflist'
    content:
      cniVersion: 0.3.1
      name: crio
      type: bridge
      bridge: cni0
      isGateway: true
      ipMasq: true
      hairpinMode: true
      ipam:
        type: host-local
        routes:
          - dst: 0.0.0.0/0
        ranges:
          - - subnet: 10.85.0.0/16
              gateway: 10.85.0.1
