---
- hosts: masters,workers
  roles:
    - name: runc
      tags: runc
    - name: containers_common
      tags: containers_common
    - name: cri_o
      tags: crio

- hosts: masters
  roles:
    - name: cni
      tags: cni

- hosts: masters,workers
  roles:
    - name: kubernetes
      tags: kubernetes
